import Config

# Runtime configuration — evaluated when the release boots, not at compile time.
# config/prod.exs only runs at `mix release` build time, so DATABASE_URL etc.
# set by Salt/launchd on the deploy target were never actually read.

if config_env() == :prod do
  # Load bot-specific config from file (generated by Salt at deployment time)
  # This avoids the macOS launchd environment variable pass-through limitation
  config_data = BotArmyLibraryRuntime.ConfigLoader.load_config()
  Application.put_env(:bot_army_library_runtime, :config_data, config_data)

  config :bot_army_companion, BotArmyCompanion.Repo,
    database:
      BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_COMPANION_DB_NAME", "ergon_companion"),
    hostname: BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_COMPANION_DB_HOST", "localhost"),
    port:
      String.to_integer(
        BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_COMPANION_DB_PORT", "30006")
      ),
    username: BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_COMPANION_DB_USER", "postgres"),
    password:
      BotArmyLibraryRuntime.ConfigLoader.get("BOT_ARMY_COMPANION_DB_PASSWORD", "postgres"),
    pool_size:
      String.to_integer(BotArmyLibraryRuntime.ConfigLoader.get("POSTGRES_POOL_SIZE", "10")),
    ssl: BotArmyLibraryRuntime.ConfigLoader.get("DATABASE_SSL") == "true",
    socket_options:
      if(BotArmyLibraryRuntime.ConfigLoader.get("DATABASE_SOCKET_TIMEOUT"),
        do: [
          connect_timeout:
            String.to_integer(BotArmyLibraryRuntime.ConfigLoader.get("DATABASE_SOCKET_TIMEOUT"))
        ],
        else: []
      )

  config :logger,
    level: String.to_atom(BotArmyLibraryRuntime.ConfigLoader.get("LOG_LEVEL", "info"))
end
